name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        opt: [none, minimal, size, speed, aggressive]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Odin
        uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: dev-2026-03

      - name: Build root lib
        shell: bash
        run: |
          if [ "${{ matrix.opt }}" = "none" ]; then
            odin build . -build-mode:lib -vet -strict-style -o:none -debug
          else
            odin build . -build-mode:lib -vet -strict-style -o:${{ matrix.opt }}
          fi

      - name: Build examples/layer1
        shell: bash
        run: |
          if [ "${{ matrix.opt }}" = "none" ]; then
            odin build ./examples/layer1/ -build-mode:lib -vet -strict-style -o:none -debug
          else
            odin build ./examples/layer1/ -build-mode:lib -vet -strict-style -o:${{ matrix.opt }}
          fi

      - name: Build examples/layer2
        shell: bash
        run: |
          if [ "${{ matrix.opt }}" = "none" ]; then
            odin build ./examples/layer2/ -build-mode:lib -vet -strict-style -o:none -debug
          else
            odin build ./examples/layer2/ -build-mode:lib -vet -strict-style -o:${{ matrix.opt }}
          fi

      - name: Build examples/layer3
        shell: bash
        run: |
          if [ "${{ matrix.opt }}" = "none" ]; then
            odin build ./examples/layer3/ -build-mode:lib -vet -strict-style -o:none -debug
          else
            odin build ./examples/layer3/ -build-mode:lib -vet -strict-style -o:${{ matrix.opt }}
          fi

      - name: Test tests/layer1
        shell: bash
        run: |
          if [ "${{ matrix.opt }}" = "none" ]; then
            odin test ./tests/layer1/ -vet -strict-style -disallow-do -o:none -debug
          else
            odin test ./tests/layer1/ -vet -strict-style -disallow-do -o:${{ matrix.opt }}
          fi

      - name: Test tests/layer2
        shell: bash
        run: |
          if [ "${{ matrix.opt }}" = "none" ]; then
            odin test ./tests/layer2/ -vet -strict-style -disallow-do -o:none -debug
          else
            odin test ./tests/layer2/ -vet -strict-style -disallow-do -o:${{ matrix.opt }}
          fi

      - name: Test tests/layer3
        shell: bash
        run: |
          if [ "${{ matrix.opt }}" = "none" ]; then
            odin test ./tests/layer3/ -vet -strict-style -disallow-do -o:none -debug
          else
            odin test ./tests/layer3/ -vet -strict-style -disallow-do -o:${{ matrix.opt }}
          fi
