name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        opt: [none, minimal, size, speed, aggressive]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Odin
        uses: laytan/setup-odin@v2
        with:
          odin-version: master

      - name: Build & Test
        run: |
          if [ "${{ matrix.opt }}" = "none" ]; then
            echo "Running NONE optimization with DEBUG"
            odin build . -no-entrypoint -vet -strict-style -o:none -debug
            odin test . -vet -strict-style -disallow-do -o:none -debug
          else
            echo "Running ${{ matrix.opt }} optimization without DEBUG"
            odin build . -no-entrypoint -vet -strict-style -o:"${{ matrix.opt }}"
            odin test . -vet -strict-style -disallow-do -o:"${{ matrix.opt }}"
          fi

      - name: Check Documentation
        run: |
          odin doc . -all-packages